### ISSUE TITLE
Passing params to a route that you're going back to

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation.github.io#30] opened 2018-02-07 21:05 UTC
https://github.com/react-navigation/react-navigation/issues/2932
https://github.com/react-navigation/react-navigation/pull/2870

**Comment by brentvatne** [comment] 2018-03-23 19:41
easier with less pushy navigate

**Comment by vonovak** [comment] 2018-09-09 01:04
dupe of https://github.com/react-navigation/react-navigation.github.io/issues/119

**Closed by vonovak** 2018-09-09 01:04 UTC
Labels: help wanted
