### ISSUE TITLE
Update headerLeft docs

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation.github.io#194] opened 2018-06-13 21:46 UTC
https://github.com/react-navigation/react-navigation/issues/4502

**Comment by vonovak** [comment] 2018-07-19 18:39
I think the issue is a dupe of https://github.com/react-navigation/react-navigation/issues/4608 this was fixed with https://github.com/react-navigation/react-navigation/pull/4679

so I'm closing

**Closed by vonovak** 2018-07-19 18:39 UTC
