### ISSUE TITLE
_react2.default.forwardRef is not a function

### ISSUE THREAD

**Issue by shigaoyu** [react-navigation/react-navigation.github.io#580] opened 2019-11-27 11:15 UTC
![image](https://user-images.githubusercontent.com/19204115/69718738-107b7580-114a-11ea-9abe-f47995fa6851.png)

使用的reactnative版本和react-navigation分别如下
    "react": "16.2.0",
    "react-native": "0.52.2",
    "react-native-gesture-handler": "^1.5.1",
    "react-native-reanimated": "^1.4.0",
    "react-native-screens": "^1.0.0-alpha.23",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.10.3"

**Comment by eriveltonelias** [comment] 2020-03-06 09:40
I'll close this issue since I don't believe it is a issue anymore, but if you still need help, please ping me and give a reproducible example.

**Closed by eriveltonelias** 2020-03-06 09:40 UTC
